package com.fdorigo.igadmin.persistent.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.fdorigo.igadmin.persistent.Client;
import com.fdorigo.igadmin.persistent.Trainer;

/**
 * Class _Location was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Location extends CayenneDataObject {

    public static final String ADDRESS_APT_PROPERTY = "addressApt";
    public static final String ADDRESS_CITY_PROPERTY = "addressCity";
    public static final String ADDRESS_NUM_PROPERTY = "addressNum";
    public static final String ADDRESS_STATE_PROPERTY = "addressState";
    public static final String ADDRESS_STREET_PROPERTY = "addressStreet";
    public static final String ADDRESS_ZIP_PROPERTY = "addressZip";
    public static final String MGR_NAME_FIRST_PROPERTY = "mgrNameFirst";
    public static final String MGR_NAME_LAST_PROPERTY = "mgrNameLast";
    public static final String NAME_PROPERTY = "name";
    public static final String OPENING_DATE_PROPERTY = "openingDate";
    public static final String PHONE_PRIMARY_PROPERTY = "phonePrimary";
    public static final String PHONE_SECONDARY_PROPERTY = "phoneSecondary";
    public static final String TRAINER_ID_PROPERTY = "trainerId";
    public static final String CLIENTS_PROPERTY = "clients";
    public static final String TO_TRAINER_PROPERTY = "toTrainer";
    public static final String TRAINERS_PROPERTY = "trainers";

    public static final String ID_PK_COLUMN = "ID";

    public void setAddressApt(String addressApt) {
        writeProperty("addressApt", addressApt);
    }
    public String getAddressApt() {
        return (String)readProperty("addressApt");
    }

    public void setAddressCity(String addressCity) {
        writeProperty("addressCity", addressCity);
    }
    public String getAddressCity() {
        return (String)readProperty("addressCity");
    }

    public void setAddressNum(String addressNum) {
        writeProperty("addressNum", addressNum);
    }
    public String getAddressNum() {
        return (String)readProperty("addressNum");
    }

    public void setAddressState(String addressState) {
        writeProperty("addressState", addressState);
    }
    public String getAddressState() {
        return (String)readProperty("addressState");
    }

    public void setAddressStreet(String addressStreet) {
        writeProperty("addressStreet", addressStreet);
    }
    public String getAddressStreet() {
        return (String)readProperty("addressStreet");
    }

    public void setAddressZip(String addressZip) {
        writeProperty("addressZip", addressZip);
    }
    public String getAddressZip() {
        return (String)readProperty("addressZip");
    }

    public void setMgrNameFirst(String mgrNameFirst) {
        writeProperty("mgrNameFirst", mgrNameFirst);
    }
    public String getMgrNameFirst() {
        return (String)readProperty("mgrNameFirst");
    }

    public void setMgrNameLast(String mgrNameLast) {
        writeProperty("mgrNameLast", mgrNameLast);
    }
    public String getMgrNameLast() {
        return (String)readProperty("mgrNameLast");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setOpeningDate(Date openingDate) {
        writeProperty("openingDate", openingDate);
    }
    public Date getOpeningDate() {
        return (Date)readProperty("openingDate");
    }

    public void setPhonePrimary(String phonePrimary) {
        writeProperty("phonePrimary", phonePrimary);
    }
    public String getPhonePrimary() {
        return (String)readProperty("phonePrimary");
    }

    public void setPhoneSecondary(String phoneSecondary) {
        writeProperty("phoneSecondary", phoneSecondary);
    }
    public String getPhoneSecondary() {
        return (String)readProperty("phoneSecondary");
    }

    public void setTrainerId(Integer trainerId) {
        writeProperty("trainerId", trainerId);
    }
    public Integer getTrainerId() {
        return (Integer)readProperty("trainerId");
    }

    public void addToClients(Client obj) {
        addToManyTarget("clients", obj, true);
    }
    public void removeFromClients(Client obj) {
        removeToManyTarget("clients", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Client> getClients() {
        return (List<Client>)readProperty("clients");
    }


    public void setToTrainer(Trainer toTrainer) {
        setToOneTarget("toTrainer", toTrainer, true);
    }

    public Trainer getToTrainer() {
        return (Trainer)readProperty("toTrainer");
    }


    public void addToTrainers(Trainer obj) {
        addToManyTarget("trainers", obj, true);
    }
    public void removeFromTrainers(Trainer obj) {
        removeToManyTarget("trainers", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Trainer> getTrainers() {
        return (List<Trainer>)readProperty("trainers");
    }


}
