package com.fdorigo.igadmin.persistent.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.fdorigo.igadmin.persistent.Client;
import com.fdorigo.igadmin.persistent.Session;

/**
 * Class _Package was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Package extends CayenneDataObject {

    public static final String DATE_PROPERTY = "date";
    public static final String MAX_SESSIONS_PROPERTY = "maxSessions";
    public static final String PRICE_PROPERTY = "price";
    public static final String CLIENT_PROPERTY = "client";
    public static final String SESSIONS_PROPERTY = "sessions";

    public static final String ID_PK_COLUMN = "ID";

    public void setDate(Date date) {
        writeProperty("date", date);
    }
    public Date getDate() {
        return (Date)readProperty("date");
    }

    public void setMaxSessions(Integer maxSessions) {
        writeProperty("maxSessions", maxSessions);
    }
    public Integer getMaxSessions() {
        return (Integer)readProperty("maxSessions");
    }

    public void setPrice(Double price) {
        writeProperty("price", price);
    }
    public Double getPrice() {
        return (Double)readProperty("price");
    }

    public void setClient(Client client) {
        setToOneTarget("client", client, true);
    }

    public Client getClient() {
        return (Client)readProperty("client");
    }


    public void addToSessions(Session obj) {
        addToManyTarget("sessions", obj, true);
    }
    public void removeFromSessions(Session obj) {
        removeToManyTarget("sessions", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Session> getSessions() {
        return (List<Session>)readProperty("sessions");
    }


}
